"""
TravelBuddy — SQLAlchemy ORM Models + Pydantic Schemas

DB Tables (Stage 1):
  users       — core identity (one row per person, keyed by Google email)
  trips       — AI-generated trip plans, FK → users
  trip_shares — share tokens for the "Share Trip" button
  api_logs    — records every AI generation call for monitoring

UUID primary keys are generated by PostgreSQL (gen_random_uuid()).
All timestamps are TIMESTAMPTZ (timezone-aware).
trip JSON columns use JSONB (binary, indexed, faster than plain JSON).
"""

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from sqlalchemy import (
    Boolean, Column, DateTime, ForeignKey,
    Integer, SmallInteger, String, Text, func, text
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship
from pydantic import BaseModel, EmailStr

from database import Base


# ─────────────────────────────────────────────
# ORM MODELS
# ─────────────────────────────────────────────

class User(Base):
    """
    Core identity table. One row per unique user.
    Supports both Google OAuth (google_id) and Email/Password auth (password_hash).
    """
    __tablename__ = "users"

    id            = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    email         = Column(String(255), unique=True, nullable=False, index=True)
    name          = Column(String(255), nullable=True)
    picture_url   = Column(Text, nullable=True)
    google_id     = Column(String(255), unique=True, nullable=True, index=True)  # Google's "sub" field
    password_hash = Column(String(255), nullable=True)                          # Bcrypt hashed password
    is_active     = Column(Boolean, default=True, nullable=False)
    created_at    = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at    = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    trips          = relationship("Trip", back_populates="user", cascade="all, delete-orphan")
    logs           = relationship("ApiLog", back_populates="user", cascade="all, delete-orphan")
    refresh_tokens = relationship("RefreshToken", back_populates="user", cascade="all, delete-orphan")


class RefreshToken(Base):
    """
    Stores long-lived refresh tokens for JWT auth session management and revocation.
    """
    __tablename__ = "refresh_tokens"

    id         = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    user_id    = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    token      = Column(String(500), unique=True, nullable=False, index=True)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    is_revoked = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    user = relationship("User", back_populates="refresh_tokens")


class Trip(Base):
    """
    AI-generated travel plans.
    - user_id: FK to users (trips are private by default)
    - user_selection: the wizard form inputs (destination, days, budget, traveler) — JSONB
    - trip_data: full AI output (hotels, itinerary, tripNote) — JSONB
    - is_public: future — if true, viewable without login via share link
    - is_deleted: soft delete — row stays in DB but is invisible to user
    Stage 2 will add: rating, tags, notes (user edits), cover_photo_url
    """
    __tablename__ = "trips"

    id             = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    user_id        = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    destination    = Column(String(500), nullable=False)
    no_of_days     = Column(SmallInteger, nullable=False)
    traveler       = Column(String(50), nullable=True)   # "solo" | "couple" | "family" | "friends"
    budget         = Column(String(50), nullable=True)   # "Budget" | "Moderate" | "Luxury"
    user_selection = Column(JSONB, nullable=False)        # full form snapshot
    trip_data      = Column(JSONB, nullable=False)        # full AI output
    is_public      = Column(Boolean, default=False, nullable=False)
    is_deleted     = Column(Boolean, default=False, nullable=False)
    created_at     = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at     = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    user   = relationship("User", back_populates="trips")
    shares = relationship("TripShare", back_populates="trip", cascade="all, delete-orphan")

class TripShare(Base):
    """
    Share tokens for the 'Share Trip' button.
    Each token maps to a trip and can optionally expire.
    Anyone with the token URL can view the trip even without login.
    Stage 2 will add: password protection, view analytics
    """
    __tablename__ = "trip_shares"

    id          = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    trip_id     = Column(UUID(as_uuid=True), ForeignKey("trips.id", ondelete="CASCADE"), nullable=False, index=True)
    share_token = Column(String(100), unique=True, nullable=False, index=True)
    expires_at  = Column(DateTime(timezone=True), nullable=True)   # NULL = never expires
    view_count  = Column(Integer, default=0, nullable=False)
    created_at  = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    trip = relationship("Trip", back_populates="shares")


class ApiLog(Base):
    """
    Logs every AI generation request for monitoring and analytics.
    user_id is nullable — logs anonymous requests too.
    Stage 2 will add: error_message, agent_steps_count, token_usage
    """
    __tablename__ = "api_logs"

    id               = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    user_id          = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    endpoint         = Column(String(200), nullable=False)
    method           = Column(String(10), nullable=False)
    status_code      = Column(SmallInteger, nullable=True)
    response_time_ms = Column(Integer, nullable=True)
    destination      = Column(String(500), nullable=True)  # for AI generation logs
    created_at       = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    user = relationship("User", back_populates="logs")


# ─────────────────────────────────────────────
# PYDANTIC REQUEST / RESPONSE SCHEMAS
# ─────────────────────────────────────────────

class Coordinates(BaseModel):
    latitude: float = 0.0
    longitude: float = 0.0

class HotelOption(BaseModel):
    hotelName: str
    hotelAddress: str
    priceRange: str
    imageUrl: str = "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80"
    rating: float = 4.2
    description: str
    coordinates: Coordinates = Coordinates()

class Activity(BaseModel):
    activityName: str
    description: str
    imageUrl: str = "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=600&q=80"
    ticketPrice: str = "Free"
    timeRange: str
    timeToTravel: str = "15 mins"
    coordinates: Coordinates = Coordinates()

class DailyPlan(BaseModel):
    dayNumber: int
    theme: str
    activities: List[Activity]

class TripPayload(BaseModel):
    """Frontend sends this when saving a trip after AI generation."""
    id: Optional[str] = None        # legacy: old timestamp-string ID (kept for compatibility)
    userEmail: str                   # used to look up / create the User row
    userSelection: Dict[str, Any]
    tripData: Dict[str, Any]

class TripResponse(BaseModel):
    """Shape of a trip returned to the frontend."""
    id: str
    userEmail: str
    userSelection: Dict[str, Any]
    tripData: Dict[str, Any]

    class Config:
        from_attributes = True

class GenerateTripRequest(BaseModel):
    destination: Any
    noOfDays: int
    traveler: str
    budget: str

class UserOut(BaseModel):
    id: Any
    email: str
    name: Optional[str] = None
    picture_url: Optional[str] = None

    class Config:
        from_attributes = True

class GoogleAuthRequest(BaseModel):
    google_access_token: Optional[str] = None
    google_id_token: Optional[str] = None

class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str = "bearer"
    user: UserOut

class RefreshTokenRequest(BaseModel):
    refresh_token: str

class UserRegisterRequest(BaseModel):
    email: EmailStr
    password: str
    name: Optional[str] = None

class UserLoginRequest(BaseModel):
    email: EmailStr
    password: str


